In [1]:
import time
time.time()

1686818868.650175

In [ ]:
#scalar addition, multiply
#ndim, shape
#1d, 1d, 3d array
#arange
#random randint
#np.full(), ones
#matrix  - identity matrix
#astype
#sliciing
#max,min, mean,

In [7]:
import timeit
#timeit.timeit(stmt="3*5")

%timeit for i in range(2000): True

44.4 µs ± 1.01 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [30]:
%%timeit -r 4 -n 1000
sum(range(n))

151 µs ± 7.22 µs per loop (mean ± std. dev. of 4 runs, 1000 loops each)


In [6]:
#%%timeit -r 4 -n 1000
import numpy as np
n=6
a=np.arange(n)
print(a)
print(type(a))
np.sum(a)

[0 1 2 3 4 5]
<class 'numpy.ndarray'>


15

In [12]:
%timeit -r 4 -n 10000 test(n)

149 µs ± 451 ns per loop (mean ± std. dev. of 4 runs, 10000 loops each)


In [13]:
%%timeit -r 4 -n 10000

import numpy as np

a = np.arange(n)


np.sum(a)

14.2 µs ± 428 ns per loop (mean ± std. dev. of 4 runs, 10000 loops each)


In [45]:
#list to numpy
l1= [1,2,3]
print(type(l1))
l2=np.array(l1)
print(type(l2))
print(l2.ndim)
print(l2.size)

<class 'list'>
<class 'numpy.ndarray'>
1
3


In [47]:
l2.shape

(3,)

In [9]:
#2D ARRAY
arr2=np.array([[1,2],[3,4],[5,6]])
print(arr2.ndim)
print(arr2.shape)
arr2.size

2
(3, 2)


6

In [17]:
#multiplication
l3=[2,3,4]
l3*3
#list cannot directly multiply


[2, 3, 4, 2, 3, 4, 2, 3, 4]

In [15]:
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [13]:
l=[1,2,3]
l*3
k=np.array(l)
k*3

array([3, 6, 9])

In [19]:
#arithmentic operations
print(arr1*2)
print(arr1/2)
print(l3+[3])
print(arr1+[3])
print(arr1-3)


[2 4 6]
[0.5 1.  1.5]
[2, 3, 4, 3]
[4 5 6]
[-2 -1  0]


In [71]:
l1=[1,2,3]
l2=[1,0,2]
l1arr=np.array(l1)
l2arr=np.array(l2)
print(l1arr-l2arr)


[0 2 1]


In [82]:
help(np.ndim)

Help on function ndim in module numpy:

ndim(a)
    Return the number of dimensions of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.  If it is not already an ndarray, a conversion is
        attempted.
    
    Returns
    -------
    number_of_dimensions : int
        The number of dimensions in `a`.  Scalars are zero-dimensional.
    
    See Also
    --------
    ndarray.ndim : equivalent method
    shape : dimensions of array
    ndarray.shape : dimensions of array
    
    Examples
    --------
    >>> np.ndim([[1,2,3],[4,5,6]])
    2
    >>> np.ndim(np.array([[1,2,3],[4,5,6]]))
    2
    >>> np.ndim(1)
    0



In [94]:
#3d array
arr4=np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[11,2,13],
               [14,15,16],
               [18,19,20]]
              ])
arr4.ndim

3

In [88]:
arr4[0][1][1]

5

In [95]:
arr4.shape


(2, 3, 3)

In [96]:
arr4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11,  2, 13],
        [14, 15, 16],
        [18, 19, 20]]])

In [97]:
arr4[1]

array([[11,  2, 13],
       [14, 15, 16],
       [18, 19, 20]])

In [99]:
arr4[1][0][0]

11

In [105]:
#2d array
arr2 = np.array([[1,2],[3,4]])
arr2.ndim
arr2[1][1]

4

In [108]:
n=4
print(range(n))
print(np.arange(n))

range(0, 4)
[0 1 2 3]


In [22]:
np.arange(1,4,0.5)
np.arange(1,4,2)

array([1, 3])

In [110]:
np.arange(4)

array([0, 1, 2, 3])

In [24]:
np.random.randint(100)



82

In [122]:
np.random.rand(4,3,3)

array([[[0.68088841, 0.51906349, 0.30742904],
        [0.10761928, 0.98502269, 0.86502019],
        [0.26581485, 0.70259937, 0.74504747]],

       [[0.67402303, 0.58224401, 0.34068058],
        [0.05886763, 0.47167893, 0.59528686],
        [0.56996176, 0.65254834, 0.27779223]],

       [[0.12771447, 0.81817236, 0.89171959],
        [0.75690356, 0.57145105, 0.47767814],
        [0.77604828, 0.12353965, 0.82732586]],

       [[0.43536427, 0.39663691, 0.83788289],
        [0.94686541, 0.28876558, 0.14424503],
        [0.60171209, 0.36653788, 0.42644675]]])

In [125]:
np.zeros(6, dtype='int64')

array([0, 0, 0, 0, 0, 0])

In [129]:
np.ones(6, dtype='int64')

array([1, 1, 1, 1, 1, 1])

In [133]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [134]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         ``np.array(fill_value).dtype``.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that pas

In [27]:
#fills values
np.full((2,2), 8)

array([[8, 8],
       [8, 8]])

In [30]:
#matrix functions
np.identity(2, dtype='int64')
#np.identity(4, dtype='int64')

array([[1, 0],
       [0, 1]])

In [31]:
#identity just creates square 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.eye(3,3,-1) #the last is k

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [144]:
np.eye(2,2,k=-1, dtype=int) #the last is k

array([[0, 0],
       [1, 0]])

In [167]:
k = np.random.randn(3,3)
k

array([[ 2.43118056,  0.40481228, -1.37343692],
       [ 1.0160123 , -0.05012943, -0.31435568],
       [ 0.15094757,  0.93955586, -1.4381242 ]])

In [168]:
np.diag(k)

array([ 2.43118056, -0.05012943, -1.4381242 ])

In [169]:
#astype - is for typecasting
k.astype(int)

array([[ 2,  0, -1],
       [ 1,  0,  0],
       [ 0,  0, -1]])

In [170]:
np.diag(k)

array([ 2.43118056, -0.05012943, -1.4381242 ])

In [171]:
l = np.array([0,1,2,3,4,5])
np.diag(l)

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])

In [175]:
%%timeit -r 4 -n 1000
sum(range(4))

289 ns ± 0.854 ns per loop (mean ± std. dev. of 4 runs, 1000 loops each)


In [185]:
%%timeit -r 4 -n 1000
np.sum(np.arange(4))

8.74 µs ± 434 ns per loop (mean ± std. dev. of 4 runs, 1000 loops each)


In [189]:
%%timeit -n 1000 -r 4
l1=[1,2,3,4,5,6]
sum(l1)

259 ns ± 34.9 ns per loop (mean ± std. dev. of 4 runs, 1000 loops each)


In [201]:
arrl=np.array([1,2,3,4,5,6])
listl = [1,2,3,4,5,6]

In [191]:
k

array([[ 2.43118056,  0.40481228, -1.37343692],
       [ 1.0160123 , -0.05012943, -0.31435568],
       [ 0.15094757,  0.93955586, -1.4381242 ]])

In [206]:
%%timeit -n 1000 -r 4
np.sum(arrl)

5.02 µs ± 1.02 µs per loop (mean ± std. dev. of 4 runs, 1000 loops each)


In [209]:
%%timeit -n 1000 -r 4
np.sum(listl)

8.29 µs ± 796 ns per loop (mean ± std. dev. of 4 runs, 1000 loops each)


In [214]:
p =  np.random.randn(3,3)
p

array([[-0.53142959, -0.03425321,  2.96407721],
       [-0.59809833, -1.04433399, -0.17477082],
       [ 1.18378159, -0.09947079,  1.4091817 ]])

In [215]:
np.max(p)

2.964077205012326

In [216]:
np.min(p)

-1.0443339932348363

In [217]:
np.mean(p)

0.3416315282925671

In [218]:
a1= np.array([1,2,4])
a2 =np.array([6,7,8])
print(np.multiply(a1,a2))

[ 6 14 32]


In [219]:
a1*a2

array([ 6, 14, 32])

In [224]:
m1 = np.array([
    [2,3,1],
    [1,5,4]
])

m2 = np.array([
    [2,3,1],
    [1,5,4],
    [4,5,6]
])

In [226]:
np.dot(m1,m2)


array([[11, 26, 20],
       [23, 48, 45]])

In [36]:
#slicing 
b = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b[-2]
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
b[3:6:2]

array([3, 5])

In [231]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [233]:
b[6:] = [12,13,14,15]

In [234]:
b

array([ 0,  1,  2,  3,  4,  5, 12, 13, 14, 15])

In [40]:
m1 = np.array([
    [1, 2],
    [3, 4]
])
print(m1.ndim)

2
